import "../scss/main.scss"
import "../scss/header-styles.scss"
import "../scss/intro-styles.scss"
import "../scss/tool-styles.scss"
import "../scss/info-blocks-styles.scss"
import "../scss/lokalise-styles.scss"
import "../scss/fonts.scss"

import "../img/HeaderPictures/logo.svg"

import "../img/IntroPictures/intro-picture.svg"

import "../img/ToolPicture/Daimler.svg"
import "../img/ToolPicture/Revolut.svg"
import "../img/ToolPicture/Specialized.svg"
import "../img/ToolPicture/Tidal.svg"
import "../img/ToolPicture/Virgin.svg"
import "../img/ToolPicture/Yelp.svg"

import "../img/InfoGifs/info_gif_1.gif"
import "../img/InfoGifs/info-gif_2.gif"
import "../img/InfoGifs/info_gif_3.gif"
import "../img/InfoGifs/info_pic.svg"

import "../img/LokaliseStaff/documents.svg"
import "../img/LokaliseStaff/games.svg"
import "../img/LokaliseStaff/ioT.svg"
import "../img/LokaliseStaff/marketing-e-mail.svg"
import "../img/LokaliseStaff/mobile-apps.svg"
import "../img/LokaliseStaff/web-apps.svg"
